apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "grafana.monitoring.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: grafana
            port:
              number: 3000
  - host: "prometheus-0.monitoring.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: prometheus-0-service
            port:
              number: 8080
  - host: "prometheus-1.monitoring.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: prometheus-1-service
            port: 
              number: 8080
  - host: "prometheus-2.monitoring.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: prometheus-2-service
            port: 
              number: 8080
  - host: "alertmanager.monitoring.com"
    http: 
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: alertmanager
            port: 
              number: 9093
  - host: "thanos-querier.monitoring.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: thanos-querier
            port: 
              number: 9090
  - host: "thanos-ruler.monitoring.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: thanos-ruler
            port: 
              number: 9090

